### ISSUE TITLE
Generate .gitignore for theme directories.

### ISSUE THREAD

**Issue by DevJMD** [plumpdigital/generator-plump-silverstripe#19]
As with a recent project, we needed to add the `/themes/<ThemeName>/css`, `/themes/<ThemeName>/js` and `/themes/<ThemeName>/images` directory to the `.gitignore` file. We could generate this as we're asking for the theme name upon initialising a project.

**Comment by jameshoward** [comment]
Already done. See https://github.com/plumpdigital/generator-plump-silverstripe/blob/master/app/templates/_gitignore

**Comment by DevJMD** [comment]
@jameshoward, mistaken this with the /build directory! Cheers.

**Comment by jameshoward** [comment]
The reason for it not being in `build/` is that it's outside of there that the compilation of source to CSS / JS and minification of images happens. Therefore it makes sense to have it in that context. Means that if you separated out just `build/` for whatever reason, those would no longer be ignored in the new context.

The `.gitignore` in `build/` only excludes parts of SilverStripe that are handled by Composer so they're relevant in that context.

**Comment by DevJMD** [comment]
@jameshoward, cheers for the heads up! :+1:
