### ISSUE TITLE
Include leading slash in build Git ignore file

### ISSUE THREAD

**Issue by jameshoward** [plumpdigital/generator-plump-silverstripe#42]
To prevent accidentally excluding any folders that are called cms, framework and vendor other than at the root level, update the generated .gitignore to use:

```
/vendor/
/cms/
/framework/
```

**Comment by JamesMD** [comment]
@jameshoward these aren't root level folders within a project (they're based inside `/build/`), am I right assuming these are just examples, but excluding the following?

E.g.,

```
/test-data/Uploads/_resampled
/build/themes/<%= config.themeName %>/css
/build/themes/<%= config.themeName %>/js
/build/themes/<%= config.themeName %>/images
```

**Comment by DevJMD** [comment]
Done in commit f87edcb3b6137f9a9b24ee82549fa8510d001166.
